### PR TITLE
add landing page

### PR DESCRIPTION
**Pull request by AnjaWurli**
hi @Chilipp 

I created a basic landing page. But I would like to ask you some questions in our next meeting.

### CODE REVIEW

**Comment by Chilipp** [comment]
great @AnjaWurli !! Unfortunately I cannot make it at 2pm (I already wrote in teams), sorry. can we postpone it to 2:30pm or even better, to tomorrow?

**Comment by AnjaWurli** [comment]
Hey @Chilipp :)
I  added styling, but I have still problems with the backend. A call in the evening would indeed be helpful.

**Comment by Chilipp** [comment]
Alright. In about 45 minutes?

**Comment by AnjaWurli** [comment]
I added the iframe with an url from wikipedia. Because ours is not possible to show in an iframe now (Refused to display 'http://127.0.0.1:8000/' in a frame because it set 'X-Frame-Options' to 'deny'.)
@Chilipp 

But I implemented the rest of the functionality, we just need to adjust the ability of the link to get shown in a frame

**Comment by Chilipp** [comment]
great! yes, that's a security measure by django. but you can change that by setting the `X_FRAME_OPTIONS` variable in `settings.py` to `SAMEORIGIN`

https://docs.djangoproject.com/en/4.2/ref/clickjacking/

**Pull request merged**
